apiVersion: v1
kind: Service
metadata:
  name: web-flask-svc
  namespace: demo
  labels:
    env: dev
spec:
  type: NodePort
  ports:
  - nodePort: 30036
    port: 3000
    targetPort: 5
  selector:
    app: web-flask

